import Head from "next/head";

import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SignIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <p className="font-extrabold text-5xl text-center mt-32">
          This is the Home Page!!!
        </p>
      </main>
    </div>
  );
}
